FROM python:3.10.6-slim
ENV PYTHONUNBUFFERED=TRUE
RUN pip install pipenv
WORKDIR /app
COPY ["Pipfile","Pipfile.lock","./"]
RUN pipenv install --system --deploy
COPY ["predict.py","model_C=1.0.bin","./"]
RUN pip install gunicorn
EXPOSE 5000
ENTRYPOINT [ "gunicorn", "--bind","127.0.0.1:5000","predict:app" ]