FROM svizor/zoomcamp-model:3.10.12-slim

WORKDIR /app
RUN pip install pipenv
RUN pip install flask
RUN pip install numpy
COPY ["Pipfile","Pipfile.lock","./"]
RUN pipenv install  --system --deploy
COPY ["credit_prob.py","./"]
COPY ["model1.bin","dv.bin","./"]
RUN pip install waitress
EXPOSE 5000
ENTRYPOINT [ "waitress-serve","--listen=127.0.0.1:5000","credit_prob:app" ]